name: Build Android and iOS
on:
  push:
    branches:
      - develop

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Build Android Debug
        run: |
          yarn assemble 
      - name: Upload .apk Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/

  build-ios:
    needs: install-and-test
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace AppCI.xcworkspace -scheme AppCI archive -archivePath AppCI.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./AppCI.xcarchive -exportPath . -exportOptionsPlist AppCI/Info.plist
          mv AppCI.ipa ../AppCI.ipa
      - name: Upload .ipa Artifact
        uses: actions/upload-artifact@v1
        with:
          name: AppCI.ipa
          path: ios/build/